Reimplemented copy! for petsvec and abstract vectors combination. The previous variant was causing a nasty error message with petsc built in debug mode.
[0]PETSC ERROR: #3 VecSetErrorIfLocked() at /home/amartin/software_installers/petsc-3.15.4-build-dbg-gnu9-mpi/include/petscvec.h:574
[0]PETSC ERROR: #4 VecGetArray() at /home/amartin/software_installers/petsc-3.15.4-build-dbg-gnu9-mpi/src/vec/vec/interface/rvector.c:1795
PETScNonLinearSolvers: Error During Test at /home/amartin/git-repos/GridapPETSc.jl/test/sequential/runtests.jl:13
  Got exception outside of a @test
  LoadError: Petsc returned with error code: 73
  Stacktrace:
    [1] macro expansion
      @ ~/git-repos/GridapPETSc.jl/src/Config.jl:88 [inlined]
    [2] get_local_vector(a::GridapPETSc.PETScVector)
      @ GridapPETSc ~/git-repos/GridapPETSc.jl/src/PETScArrays.jl:176
    [3] copy!(vec::Vector{Float64}, petscvec::GridapPETSc.PETScVector)
      @ GridapPETSc ~/git-repos/GridapPETSc.jl/src/PETScArrays.jl:124
    [4] copy!(a::Vector{Float64}, petsc_vec::GridapPETSc.PETSC.Vec)
      @ GridapPETSc ~/git-repos/GridapPETSc.jl/src/PETScArrays.jl:112
    [5] snes_residual(csnes::Ptr{Nothing}, cx::Ptr{Nothing}, cfx::Ptr{Nothing}, ctx::Ptr{Nothing})
      @ GridapPETSc ~/git-repos/GridapPETSc.jl/src/PETScNonlinearSolvers.jl:42
    [6] SNESSolve
      @ ~/git-repos/GridapPETSc.jl/src/PETSC.jl:62 [inlined]
    [7] macro expansion
      @ ~/git-repos/GridapPETSc.jl/src/Config.jl:86 [inlined]
    [8] solve!(x::Vector{Float64}, nls::GridapPETSc.PETScNonlinearSolver, op::Gridap.Algebra.NonlinearOperatorMock)
      @ GridapPETSc ~/git-repos/GridapPETSc.jl/src/PETScNonlinearSolvers.jl:183
    [9] test_nonlinear_solver(nls::GridapPETSc.PETScNonlinearSolver, op::Gridap.Algebra.NonlinearOperatorMock, x0::Vector{Float64}, x::Vector{Float64}, pred::typeof(isapprox))
      @ Gridap.Algebra ~/.julia/packages/Gridap/AfDIn/src/Algebra/NonlinearSolvers.jl:62
   [10] test_nonlinear_solver(nls::GridapPETSc.PETScNonlinearSolver, op::Gridap.Algebra.NonlinearOperatorMock, x0::Vector{Float64}, x::Vector{Float64})
      @ Gridap.Algebra ~/.julia/packages/Gridap/AfDIn/src/Algebra/NonlinearSolvers.jl:61
   [11] top-level scope
      @ ~/git-repos/GridapPETSc.jl/test/sequential/PETScNonlinearSolversTests.jl:15
   [12] include(mod::Module, _path::String)
      @ Base ./Base.jl:386
   [13] include
      @ ~/git-repos/GridapPETSc.jl/test/sequential/runtests.jl:1 [inlined]
   [14] macro expansion
      @ ~/git-repos/GridapPETSc.jl/test/sequential/runtests.jl:13 [inlined]
   [15] macro expansion
      @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
   [16] macro expansion
      @ ~/git-repos/GridapPETSc.jl/test/sequential/runtests.jl:13 [inlined]
   [17] top-level scope
      @ ./timing.jl:210 [inlined]
   [18] top-level scope
      @ ~/git-repos/GridapPETSc.jl/test/sequential/runtests.jl:0
   [19] include(fname::String)
      @ Base.MainInclude ./client.jl:444
   [20] top-level scope
      @ REPL[3]:1
   [21] eval
      @ ./boot.jl:360 [inlined]
   [22] eval
      @ ./Base.jl:39 [inlined]
   [23] repleval(m::Module, code::Expr, #unused#::String)
      @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-1.4.3/scripts/packages/VSCodeServer/src/repl.jl:157
   [24] (::VSCodeServer.var"#69#71"{Module, Expr, REPL.LineEditREPL, REPL.LineEdit.Prompt})()
      @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-1.4.3/scripts/packages/VSCodeServer/src/repl.jl:123
   [25] with_logstate(f::Function, logstate::Any)
      @ Base.CoreLogging ./logging.jl:491
   [26] with_logger
      @ ./logging.jl:603 [inlined]
   [27] (::VSCodeServer.var"#68#70"{Module, Expr, REPL.LineEditREPL, REPL.LineEdit.Prompt})()
      @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-1.4.3/scripts/packages/VSCodeServer/src/repl.jl:124
   [28] #invokelatest#2
      @ ./essentials.jl:708 [inlined]
   [29] invokelatest(::Any)
      @ Base ./essentials.jl:706
   [30] macro expansion
      @ ~/.vscode/extensions/julialang.language-julia-1.4.3/scripts/packages/VSCodeServer/src/eval.jl:34 [inlined]
   [31] (::VSCodeServer.var"#53#54")()
      @ VSCodeServer ./task.jl:411
  in expression starting at /home/amartin/git-repos/GridapPETSc.jl/test/sequential/PETScNonlinearSolversTests.jl:1
Test Summary:         | Error  Total
PETScNonLinearSolvers |     1      1
ERROR: LoadError: Some tests did not pass: 0 passed, 0 failed, 1 errored, 0 broken.
in expression starting at /home/amartin/git-repos/GridapPETSc.jl/test/sequential/runtests.jl:1